#!/usr/bin/env bash
# Displays To infinity and beyond and traps SIGTERM signal

trap sig_nal SIGTERM

sig_nal()
{
    echo "I am invincible!!!"
}

while true
do
    echo "To infinity and beyond"
    sleep 2
done
