#!/usr/bin/env bash
# Displays To infinity and beyond and traps SIGTERM signal


sig_nal() {
	echo "I am invicible!!!"
}
trap sig_nal SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
